dist: trusty
addons:
  chrome: stable
notifications:
  email: false

rvm:
  - 2.5.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: EibSqr0uzGbdVS8Qx75YOG0wU7idjR2gP+2zukhFUNU3gAn97U58UpC08wwiPW7Rf/B78fqDyNcYBf0FggkH1FBXGXhB1xOyH3TONvmzbOcIsoMhXh3Sh3tLuaqknDHTPFmAKKdmvI3pLUCu+9WvFw9JP5qj9zXDjz2xO4jizo4=

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - bin/rails db:test:prepare

sudo: false
language: ruby
cache: bundler

jdk: oraclejdk8
