superadmin_workgroups:
  - dlss:exhibits-admin
default_contact_email: exhibits-feedback@lists.stanford.edu
geonames_username: ''
stacks:
  iiif_url: 'https://stacks.stanford.edu/image/iiif'
  file_url: 'https://stacks.stanford.edu/file'

purl:
  iiif_manifest_url: 'https://purl.stanford.edu/%{druid}/iiif/manifest'
sidekiq:
  logger_level: 'Logger::INFO' # The default from Sidekiq
feature_flags:
  themes: false
  bibliography_resource: false
  index_related_content: false # A feature that will index related SDR content. Initial implemented for Parker's IIIF AnnotationLists
  add_resource_type_index_field: false # Should the resource type field be added as an index/show field. For some exhibits this is desirable
traject:
  processing_thread_pool: 1
iiif_dnd_base_url: https://library.stanford.edu/projects/international-image-interoperability-framework/viewers?%{query}
action_mailer:
  default_options:
    from: "example-team@example.com"
  default_url_options:
    host: "example.com"

harvestdor:
  log_dir: log/gdor_logs
  log_name: gdor.log
  purl: https://purl.stanford.edu

gdor:
  service_url: https://dorfetcher-url
  skip_heartbeat: true
