superadmin_workgroups:
  - dlss:exhibits-admin
default_contact_email: exhibits-feedback@lists.stanford.edu
geonames_username: ''
stacks:
  iiif_url: 'https://stacks.stanford.edu/image/iiif'
  file_url: 'https://stacks.stanford.edu/file'

purl:
  iiif_manifest_url: 'https://purl.stanford.edu/%{druid}/iiif/manifest.json'
sidekiq:
  logger_level: 'Logger::INFO' # The default from Sidekiq
feature_flags:
  themes: false
  bibliography_resource: false
traject:
  processing_thread_pool: 1
