searchworks:
  api:
    prefix: "http://searchworks.stanford.edu/view/"
    suffix: ".mobile"
  link:
    prefix: "http://searchworks.stanford.edu/view/"
purl:
  link:
    prefix: "http://purl.stanford.edu/"
feature_flags:
  themes: true
  bibliography_resource: true
  test-flag-exhibit-slug:
    test_thing: true
    index_related_content: true
