searchworks:
  api:
    prefix: "http://searchworks.stanford.edu/view/"
    suffix: ".mobile"
  link:
    prefix: "http://searchworks.stanford.edu/view/"
purl:
  link:
    prefix: "http://purl.stanford.edu/"
sync_bibliography_service:
  enabled: true # FeatureFlag: SyncBibliograhyService
feature_flags:
  themes: true
  bibliography_resource: true
